package persistence

var requiredSQLiteTables = []string{
	"schema_metadata",
	"scan_batches",
	"batch_search_profile_terms",
	"batch_groups",
	"raw_post_occurrences",
	"evaluated_posts",
	"evaluated_post_reasons",
	"bucketed_posts",
	"bucketed_post_reasons",
	"leads",
	"lead_key_need_product_evidence",
	"lead_key_need_buyer_intent_evidence",
	"lead_need_product_evidence",
	"lead_need_buyer_intent_evidence",
	"lead_sources",
	"lead_outcomes",
	"lead_outcome_blocklist_reasons",
	"lead_outcome_application_reasons",
	"unaggregated_posts",
	"unaggregated_candidate_product_evidence",
	"unaggregated_candidate_buyer_intent_evidence",
	"unaggregated_post_reasons",
	"source_conflicts",
	"source_conflict_candidate_product_evidence",
	"source_conflict_candidate_buyer_intent_evidence",
	"source_conflict_reasons",
	"group_summaries",
}

var requiredSQLiteIndexes = []string{
	"idx_scan_batches_batch_record_id_unique",
	"idx_batch_search_profile_terms_batch_fk",
	"idx_batch_search_profile_terms_position_unique",
	"idx_batch_groups_batch_fk",
	"idx_batch_groups_position_unique",
	"idx_batch_groups_group_id_unique",
	"idx_raw_post_occurrences_batch_fk",
	"idx_raw_post_occurrences_group_fk",
	"idx_raw_post_occurrences_flattened_position_unique",
	"idx_raw_post_occurrences_group_post_position_unique",
	"idx_evaluated_posts_batch_fk",
	"idx_evaluated_posts_post_fk",
	"idx_evaluated_posts_position_unique",
	"idx_evaluated_post_reasons_parent_fk",
	"idx_evaluated_post_reasons_position_unique",
	"idx_bucketed_posts_batch_fk",
	"idx_bucketed_posts_post_fk",
	"idx_bucketed_posts_position_unique",
	"idx_bucketed_post_reasons_parent_fk",
	"idx_bucketed_post_reasons_position_unique",
	"idx_leads_batch_fk",
	"idx_leads_position_unique",
	"idx_lead_key_need_product_evidence_parent_fk",
	"idx_lead_key_need_product_evidence_position_unique",
	"idx_lead_key_need_buyer_intent_evidence_parent_fk",
	"idx_lead_key_need_buyer_intent_evidence_position_unique",
	"idx_lead_need_product_evidence_parent_fk",
	"idx_lead_need_product_evidence_position_unique",
	"idx_lead_need_buyer_intent_evidence_parent_fk",
	"idx_lead_need_buyer_intent_evidence_position_unique",
	"idx_lead_sources_parent_fk",
	"idx_lead_sources_post_fk",
	"idx_lead_sources_position_unique",
	"idx_lead_outcomes_batch_fk",
	"idx_lead_outcomes_lead_fk",
	"idx_lead_outcomes_position_unique",
	"idx_lead_outcome_blocklist_reasons_parent_fk",
	"idx_lead_outcome_blocklist_reasons_position_unique",
	"idx_lead_outcome_application_reasons_parent_fk",
	"idx_lead_outcome_application_reasons_position_unique",
	"idx_unaggregated_posts_batch_fk",
	"idx_unaggregated_posts_post_fk",
	"idx_unaggregated_posts_position_unique",
	"idx_unaggregated_candidate_product_evidence_parent_fk",
	"idx_unaggregated_candidate_product_evidence_position_unique",
	"idx_unaggregated_candidate_buyer_intent_evidence_parent_fk",
	"idx_unaggregated_candidate_buyer_intent_evidence_position_unique",
	"idx_unaggregated_post_reasons_parent_fk",
	"idx_unaggregated_post_reasons_position_unique",
	"idx_source_conflicts_batch_fk",
	"idx_source_conflicts_post_fk",
	"idx_source_conflicts_existing_post_fk",
	"idx_source_conflicts_position_unique",
	"idx_source_conflict_candidate_product_evidence_parent_fk",
	"idx_source_conflict_candidate_product_evidence_position_unique",
	"idx_source_conflict_candidate_buyer_intent_evidence_parent_fk",
	"idx_source_conflict_candidate_buyer_intent_evidence_position_unique",
	"idx_source_conflict_reasons_parent_fk",
	"idx_source_conflict_reasons_position_unique",
	"idx_group_summaries_batch_fk",
	"idx_group_summaries_group_fk",
	"idx_group_summaries_position_unique",
}

func sqliteSchemaStatements() []string {
	statements := make([]string, 0, len(sqliteV1TableStatements)+len(sqliteV1IndexStatements))
	statements = append(statements, sqliteV1TableStatements...)
	statements = append(statements, sqliteV1IndexStatements...)
	return statements
}

var sqliteV1TableStatements = []string{
	`CREATE TABLE schema_metadata (
		metadata_pk INTEGER PRIMARY KEY CHECK (metadata_pk = 1),
		current_schema_version INTEGER NOT NULL
	)`,
	`CREATE TABLE scan_batches (
		batch_pk INTEGER PRIMARY KEY,
		batch_record_id TEXT NOT NULL,
		schema_version INTEGER NOT NULL CHECK (schema_version = 1),
		scan_date TEXT NOT NULL,
		scan_start_of_day TEXT NOT NULL,
		scan_started_at TEXT NOT NULL,
		scan_timezone TEXT NOT NULL,
		search_profile_id TEXT NOT NULL,
		search_profile_display_name TEXT NOT NULL,
		search_profile_is_enabled INTEGER NOT NULL CHECK (search_profile_is_enabled IN (0, 1)),
		geographic_mode TEXT NOT NULL,
		summary_group_count INTEGER NOT NULL CHECK (summary_group_count >= 0),
		summary_input_post_count INTEGER NOT NULL CHECK (summary_input_post_count >= 0),
		summary_evaluated_post_count INTEGER NOT NULL CHECK (summary_evaluated_post_count >= 0),
		summary_include_post_count INTEGER NOT NULL CHECK (summary_include_post_count >= 0),
		summary_review_post_count INTEGER NOT NULL CHECK (summary_review_post_count >= 0),
		summary_excluded_post_count INTEGER NOT NULL CHECK (summary_excluded_post_count >= 0),
		summary_aggregated_lead_count INTEGER NOT NULL CHECK (summary_aggregated_lead_count >= 0),
		summary_allowed_lead_count INTEGER NOT NULL CHECK (summary_allowed_lead_count >= 0),
		summary_blocked_lead_count INTEGER NOT NULL CHECK (summary_blocked_lead_count >= 0),
		summary_unresolved_lead_count INTEGER NOT NULL CHECK (summary_unresolved_lead_count >= 0),
		summary_unaggregated_post_count INTEGER NOT NULL CHECK (summary_unaggregated_post_count >= 0),
		summary_source_conflict_count INTEGER NOT NULL CHECK (summary_source_conflict_count >= 0),
		summary_allowed_lead_source_post_count INTEGER NOT NULL CHECK (summary_allowed_lead_source_post_count >= 0),
		summary_blocked_lead_source_post_count INTEGER NOT NULL CHECK (summary_blocked_lead_source_post_count >= 0)
	)`,
	`CREATE TABLE batch_search_profile_terms (
		term_pk INTEGER PRIMARY KEY,
		batch_pk INTEGER NOT NULL REFERENCES scan_batches(batch_pk),
		term_kind TEXT NOT NULL CHECK (term_kind IN ('product', 'buyer_intent', 'noise')),
		term_position INTEGER NOT NULL CHECK (term_position >= 0),
		term_value TEXT NOT NULL
	)`,
	`CREATE TABLE batch_groups (
		group_pk INTEGER PRIMARY KEY,
		batch_pk INTEGER NOT NULL REFERENCES scan_batches(batch_pk),
		group_position INTEGER NOT NULL CHECK (group_position >= 0),
		group_id TEXT NOT NULL,
		group_name TEXT NOT NULL
	)`,
	`CREATE TABLE raw_post_occurrences (
		post_occurrence_pk INTEGER PRIMARY KEY,
		batch_pk INTEGER NOT NULL REFERENCES scan_batches(batch_pk),
		group_pk INTEGER NOT NULL REFERENCES batch_groups(group_pk),
		group_position INTEGER NOT NULL CHECK (group_position >= 0),
		group_post_position INTEGER NOT NULL CHECK (group_post_position >= 0),
		flattened_position INTEGER NOT NULL CHECK (flattened_position >= 0),
		post_id TEXT NOT NULL,
		group_id TEXT NOT NULL,
		group_name TEXT NOT NULL,
		post_url TEXT NOT NULL,
		author_facebook_user_id TEXT NOT NULL,
		author_canonical_profile_url TEXT NOT NULL,
		author_username TEXT NOT NULL,
		author_display_name TEXT NOT NULL,
		body TEXT NOT NULL,
		created_at TEXT NOT NULL,
		captured_at TEXT NOT NULL
	)`,
	`CREATE TABLE evaluated_posts (
		evaluated_post_pk INTEGER PRIMARY KEY,
		batch_pk INTEGER NOT NULL REFERENCES scan_batches(batch_pk),
		post_occurrence_pk INTEGER NOT NULL REFERENCES raw_post_occurrences(post_occurrence_pk),
		evaluated_position INTEGER NOT NULL CHECK (evaluated_position >= 0),
		decision TEXT NOT NULL CHECK (decision IN ('include', 'review', 'exclude')),
		geographic_class TEXT NOT NULL,
		geographic_reason_set_present INTEGER NOT NULL CHECK (geographic_reason_set_present IN (0, 1))
	)`,
	`CREATE TABLE evaluated_post_reasons (
		reason_pk INTEGER PRIMARY KEY,
		evaluated_post_pk INTEGER NOT NULL REFERENCES evaluated_posts(evaluated_post_pk),
		reason_category TEXT NOT NULL CHECK (reason_category IN ('rule', 'geographic')),
		reason_position INTEGER NOT NULL CHECK (reason_position >= 0),
		reason_code TEXT NOT NULL
	)`,
	`CREATE TABLE bucketed_posts (
		bucketed_post_pk INTEGER PRIMARY KEY,
		batch_pk INTEGER NOT NULL REFERENCES scan_batches(batch_pk),
		bucket TEXT NOT NULL CHECK (bucket IN ('include', 'review', 'exclude')),
		bucket_position INTEGER NOT NULL CHECK (bucket_position >= 0),
		post_occurrence_pk INTEGER NOT NULL REFERENCES raw_post_occurrences(post_occurrence_pk),
		decision TEXT NOT NULL CHECK (decision IN ('include', 'review', 'exclude')),
		geographic_class TEXT NOT NULL
	)`,
	`CREATE TABLE bucketed_post_reasons (
		reason_pk INTEGER PRIMARY KEY,
		bucketed_post_pk INTEGER NOT NULL REFERENCES bucketed_posts(bucketed_post_pk),
		reason_category TEXT NOT NULL CHECK (reason_category IN ('rule', 'geographic')),
		reason_position INTEGER NOT NULL CHECK (reason_position >= 0),
		reason_code TEXT NOT NULL
	)`,
	`CREATE TABLE leads (
		lead_pk INTEGER PRIMARY KEY,
		batch_pk INTEGER NOT NULL REFERENCES scan_batches(batch_pk),
		lead_position INTEGER NOT NULL CHECK (lead_position >= 0),
		lead_key_value TEXT NOT NULL,
		lead_key_author_kind TEXT NOT NULL,
		lead_key_author_value TEXT NOT NULL,
		lead_key_need_search_profile_id TEXT NOT NULL,
		lead_key_need_normalized_body TEXT NOT NULL,
		lead_key_need_body_fingerprint TEXT NOT NULL,
		author_kind TEXT NOT NULL,
		author_value TEXT NOT NULL,
		need_search_profile_id TEXT NOT NULL,
		need_normalized_body TEXT NOT NULL,
		need_body_fingerprint TEXT NOT NULL
	)`,
	`CREATE TABLE lead_key_need_product_evidence (
		evidence_pk INTEGER PRIMARY KEY,
		lead_pk INTEGER NOT NULL REFERENCES leads(lead_pk),
		evidence_position INTEGER NOT NULL CHECK (evidence_position >= 0),
		evidence_value TEXT NOT NULL
	)`,
	`CREATE TABLE lead_key_need_buyer_intent_evidence (
		evidence_pk INTEGER PRIMARY KEY,
		lead_pk INTEGER NOT NULL REFERENCES leads(lead_pk),
		evidence_position INTEGER NOT NULL CHECK (evidence_position >= 0),
		evidence_value TEXT NOT NULL
	)`,
	`CREATE TABLE lead_need_product_evidence (
		evidence_pk INTEGER PRIMARY KEY,
		lead_pk INTEGER NOT NULL REFERENCES leads(lead_pk),
		evidence_position INTEGER NOT NULL CHECK (evidence_position >= 0),
		evidence_value TEXT NOT NULL
	)`,
	`CREATE TABLE lead_need_buyer_intent_evidence (
		evidence_pk INTEGER PRIMARY KEY,
		lead_pk INTEGER NOT NULL REFERENCES leads(lead_pk),
		evidence_position INTEGER NOT NULL CHECK (evidence_position >= 0),
		evidence_value TEXT NOT NULL
	)`,
	`CREATE TABLE lead_sources (
		lead_source_pk INTEGER PRIMARY KEY,
		lead_pk INTEGER NOT NULL REFERENCES leads(lead_pk),
		source_position INTEGER NOT NULL CHECK (source_position >= 0),
		post_occurrence_pk INTEGER NOT NULL REFERENCES raw_post_occurrences(post_occurrence_pk),
		source_key_kind TEXT NOT NULL,
		source_key_value TEXT NOT NULL
	)`,
	`CREATE TABLE lead_outcomes (
		lead_outcome_pk INTEGER PRIMARY KEY,
		batch_pk INTEGER NOT NULL REFERENCES scan_batches(batch_pk),
		lead_pk INTEGER NOT NULL REFERENCES leads(lead_pk),
		outcome_bucket TEXT NOT NULL CHECK (outcome_bucket IN ('allowed', 'blocked', 'unresolved')),
		bucket_position INTEGER NOT NULL CHECK (bucket_position >= 0),
		match_outcome TEXT NOT NULL,
		match_author_key_kind TEXT NOT NULL,
		match_author_key_value TEXT NOT NULL,
		matched_entry_key_kind TEXT NOT NULL,
		matched_entry_key_value TEXT NOT NULL,
		matched_entry_display_name TEXT NOT NULL
	)`,
	`CREATE TABLE lead_outcome_blocklist_reasons (
		reason_pk INTEGER PRIMARY KEY,
		lead_outcome_pk INTEGER NOT NULL REFERENCES lead_outcomes(lead_outcome_pk),
		reason_position INTEGER NOT NULL CHECK (reason_position >= 0),
		reason_code TEXT NOT NULL
	)`,
	`CREATE TABLE lead_outcome_application_reasons (
		reason_pk INTEGER PRIMARY KEY,
		lead_outcome_pk INTEGER NOT NULL REFERENCES lead_outcomes(lead_outcome_pk),
		reason_position INTEGER NOT NULL CHECK (reason_position >= 0),
		reason_code TEXT NOT NULL
	)`,
	`CREATE TABLE unaggregated_posts (
		unaggregated_pk INTEGER PRIMARY KEY,
		batch_pk INTEGER NOT NULL REFERENCES scan_batches(batch_pk),
		unaggregated_position INTEGER NOT NULL CHECK (unaggregated_position >= 0),
		post_occurrence_pk INTEGER NOT NULL REFERENCES raw_post_occurrences(post_occurrence_pk),
		candidate_author_kind TEXT NOT NULL,
		candidate_author_value TEXT NOT NULL,
		candidate_need_search_profile_id TEXT NOT NULL,
		candidate_need_normalized_body TEXT NOT NULL,
		candidate_need_body_fingerprint TEXT NOT NULL,
		source_key_kind TEXT NOT NULL,
		source_key_value TEXT NOT NULL
	)`,
	`CREATE TABLE unaggregated_candidate_product_evidence (
		evidence_pk INTEGER PRIMARY KEY,
		unaggregated_pk INTEGER NOT NULL REFERENCES unaggregated_posts(unaggregated_pk),
		evidence_position INTEGER NOT NULL CHECK (evidence_position >= 0),
		evidence_value TEXT NOT NULL
	)`,
	`CREATE TABLE unaggregated_candidate_buyer_intent_evidence (
		evidence_pk INTEGER PRIMARY KEY,
		unaggregated_pk INTEGER NOT NULL REFERENCES unaggregated_posts(unaggregated_pk),
		evidence_position INTEGER NOT NULL CHECK (evidence_position >= 0),
		evidence_value TEXT NOT NULL
	)`,
	`CREATE TABLE unaggregated_post_reasons (
		reason_pk INTEGER PRIMARY KEY,
		unaggregated_pk INTEGER NOT NULL REFERENCES unaggregated_posts(unaggregated_pk),
		reason_position INTEGER NOT NULL CHECK (reason_position >= 0),
		reason_code TEXT NOT NULL
	)`,
	`CREATE TABLE source_conflicts (
		source_conflict_pk INTEGER PRIMARY KEY,
		batch_pk INTEGER NOT NULL REFERENCES scan_batches(batch_pk),
		conflict_position INTEGER NOT NULL CHECK (conflict_position >= 0),
		post_occurrence_pk INTEGER NOT NULL REFERENCES raw_post_occurrences(post_occurrence_pk),
		existing_post_occurrence_pk INTEGER NOT NULL REFERENCES raw_post_occurrences(post_occurrence_pk),
		existing_source_key_kind TEXT NOT NULL,
		existing_source_key_value TEXT NOT NULL,
		candidate_author_kind TEXT NOT NULL,
		candidate_author_value TEXT NOT NULL,
		candidate_need_search_profile_id TEXT NOT NULL,
		candidate_need_normalized_body TEXT NOT NULL,
		candidate_need_body_fingerprint TEXT NOT NULL,
		source_key_kind TEXT NOT NULL,
		source_key_value TEXT NOT NULL
	)`,
	`CREATE TABLE source_conflict_candidate_product_evidence (
		evidence_pk INTEGER PRIMARY KEY,
		source_conflict_pk INTEGER NOT NULL REFERENCES source_conflicts(source_conflict_pk),
		evidence_position INTEGER NOT NULL CHECK (evidence_position >= 0),
		evidence_value TEXT NOT NULL
	)`,
	`CREATE TABLE source_conflict_candidate_buyer_intent_evidence (
		evidence_pk INTEGER PRIMARY KEY,
		source_conflict_pk INTEGER NOT NULL REFERENCES source_conflicts(source_conflict_pk),
		evidence_position INTEGER NOT NULL CHECK (evidence_position >= 0),
		evidence_value TEXT NOT NULL
	)`,
	`CREATE TABLE source_conflict_reasons (
		reason_pk INTEGER PRIMARY KEY,
		source_conflict_pk INTEGER NOT NULL REFERENCES source_conflicts(source_conflict_pk),
		reason_position INTEGER NOT NULL CHECK (reason_position >= 0),
		reason_code TEXT NOT NULL
	)`,
	`CREATE TABLE group_summaries (
		group_summary_pk INTEGER PRIMARY KEY,
		batch_pk INTEGER NOT NULL REFERENCES scan_batches(batch_pk),
		group_pk INTEGER NOT NULL REFERENCES batch_groups(group_pk),
		group_position INTEGER NOT NULL CHECK (group_position >= 0),
		group_id TEXT NOT NULL,
		input_post_count INTEGER NOT NULL CHECK (input_post_count >= 0),
		evaluated_post_count INTEGER NOT NULL CHECK (evaluated_post_count >= 0),
		include_post_count INTEGER NOT NULL CHECK (include_post_count >= 0),
		review_post_count INTEGER NOT NULL CHECK (review_post_count >= 0),
		excluded_post_count INTEGER NOT NULL CHECK (excluded_post_count >= 0)
	)`,
}

var sqliteV1IndexStatements = []string{
	`CREATE UNIQUE INDEX idx_scan_batches_batch_record_id_unique ON scan_batches(batch_record_id)`,
	`CREATE INDEX idx_batch_search_profile_terms_batch_fk ON batch_search_profile_terms(batch_pk)`,
	`CREATE UNIQUE INDEX idx_batch_search_profile_terms_position_unique ON batch_search_profile_terms(batch_pk, term_kind, term_position)`,
	`CREATE INDEX idx_batch_groups_batch_fk ON batch_groups(batch_pk)`,
	`CREATE UNIQUE INDEX idx_batch_groups_position_unique ON batch_groups(batch_pk, group_position)`,
	`CREATE UNIQUE INDEX idx_batch_groups_group_id_unique ON batch_groups(batch_pk, group_id)`,
	`CREATE INDEX idx_raw_post_occurrences_batch_fk ON raw_post_occurrences(batch_pk)`,
	`CREATE INDEX idx_raw_post_occurrences_group_fk ON raw_post_occurrences(group_pk)`,
	`CREATE UNIQUE INDEX idx_raw_post_occurrences_flattened_position_unique ON raw_post_occurrences(batch_pk, flattened_position)`,
	`CREATE UNIQUE INDEX idx_raw_post_occurrences_group_post_position_unique ON raw_post_occurrences(batch_pk, group_pk, group_post_position)`,
	`CREATE INDEX idx_evaluated_posts_batch_fk ON evaluated_posts(batch_pk)`,
	`CREATE INDEX idx_evaluated_posts_post_fk ON evaluated_posts(post_occurrence_pk)`,
	`CREATE UNIQUE INDEX idx_evaluated_posts_position_unique ON evaluated_posts(batch_pk, evaluated_position)`,
	`CREATE INDEX idx_evaluated_post_reasons_parent_fk ON evaluated_post_reasons(evaluated_post_pk)`,
	`CREATE UNIQUE INDEX idx_evaluated_post_reasons_position_unique ON evaluated_post_reasons(evaluated_post_pk, reason_category, reason_position)`,
	`CREATE INDEX idx_bucketed_posts_batch_fk ON bucketed_posts(batch_pk)`,
	`CREATE INDEX idx_bucketed_posts_post_fk ON bucketed_posts(post_occurrence_pk)`,
	`CREATE UNIQUE INDEX idx_bucketed_posts_position_unique ON bucketed_posts(batch_pk, bucket, bucket_position)`,
	`CREATE INDEX idx_bucketed_post_reasons_parent_fk ON bucketed_post_reasons(bucketed_post_pk)`,
	`CREATE UNIQUE INDEX idx_bucketed_post_reasons_position_unique ON bucketed_post_reasons(bucketed_post_pk, reason_category, reason_position)`,
	`CREATE INDEX idx_leads_batch_fk ON leads(batch_pk)`,
	`CREATE UNIQUE INDEX idx_leads_position_unique ON leads(batch_pk, lead_position)`,
	`CREATE INDEX idx_lead_key_need_product_evidence_parent_fk ON lead_key_need_product_evidence(lead_pk)`,
	`CREATE UNIQUE INDEX idx_lead_key_need_product_evidence_position_unique ON lead_key_need_product_evidence(lead_pk, evidence_position)`,
	`CREATE INDEX idx_lead_key_need_buyer_intent_evidence_parent_fk ON lead_key_need_buyer_intent_evidence(lead_pk)`,
	`CREATE UNIQUE INDEX idx_lead_key_need_buyer_intent_evidence_position_unique ON lead_key_need_buyer_intent_evidence(lead_pk, evidence_position)`,
	`CREATE INDEX idx_lead_need_product_evidence_parent_fk ON lead_need_product_evidence(lead_pk)`,
	`CREATE UNIQUE INDEX idx_lead_need_product_evidence_position_unique ON lead_need_product_evidence(lead_pk, evidence_position)`,
	`CREATE INDEX idx_lead_need_buyer_intent_evidence_parent_fk ON lead_need_buyer_intent_evidence(lead_pk)`,
	`CREATE UNIQUE INDEX idx_lead_need_buyer_intent_evidence_position_unique ON lead_need_buyer_intent_evidence(lead_pk, evidence_position)`,
	`CREATE INDEX idx_lead_sources_parent_fk ON lead_sources(lead_pk)`,
	`CREATE INDEX idx_lead_sources_post_fk ON lead_sources(post_occurrence_pk)`,
	`CREATE UNIQUE INDEX idx_lead_sources_position_unique ON lead_sources(lead_pk, source_position)`,
	`CREATE INDEX idx_lead_outcomes_batch_fk ON lead_outcomes(batch_pk)`,
	`CREATE INDEX idx_lead_outcomes_lead_fk ON lead_outcomes(lead_pk)`,
	`CREATE UNIQUE INDEX idx_lead_outcomes_position_unique ON lead_outcomes(batch_pk, outcome_bucket, bucket_position)`,
	`CREATE INDEX idx_lead_outcome_blocklist_reasons_parent_fk ON lead_outcome_blocklist_reasons(lead_outcome_pk)`,
	`CREATE UNIQUE INDEX idx_lead_outcome_blocklist_reasons_position_unique ON lead_outcome_blocklist_reasons(lead_outcome_pk, reason_position)`,
	`CREATE INDEX idx_lead_outcome_application_reasons_parent_fk ON lead_outcome_application_reasons(lead_outcome_pk)`,
	`CREATE UNIQUE INDEX idx_lead_outcome_application_reasons_position_unique ON lead_outcome_application_reasons(lead_outcome_pk, reason_position)`,
	`CREATE INDEX idx_unaggregated_posts_batch_fk ON unaggregated_posts(batch_pk)`,
	`CREATE INDEX idx_unaggregated_posts_post_fk ON unaggregated_posts(post_occurrence_pk)`,
	`CREATE UNIQUE INDEX idx_unaggregated_posts_position_unique ON unaggregated_posts(batch_pk, unaggregated_position)`,
	`CREATE INDEX idx_unaggregated_candidate_product_evidence_parent_fk ON unaggregated_candidate_product_evidence(unaggregated_pk)`,
	`CREATE UNIQUE INDEX idx_unaggregated_candidate_product_evidence_position_unique ON unaggregated_candidate_product_evidence(unaggregated_pk, evidence_position)`,
	`CREATE INDEX idx_unaggregated_candidate_buyer_intent_evidence_parent_fk ON unaggregated_candidate_buyer_intent_evidence(unaggregated_pk)`,
	`CREATE UNIQUE INDEX idx_unaggregated_candidate_buyer_intent_evidence_position_unique ON unaggregated_candidate_buyer_intent_evidence(unaggregated_pk, evidence_position)`,
	`CREATE INDEX idx_unaggregated_post_reasons_parent_fk ON unaggregated_post_reasons(unaggregated_pk)`,
	`CREATE UNIQUE INDEX idx_unaggregated_post_reasons_position_unique ON unaggregated_post_reasons(unaggregated_pk, reason_position)`,
	`CREATE INDEX idx_source_conflicts_batch_fk ON source_conflicts(batch_pk)`,
	`CREATE INDEX idx_source_conflicts_post_fk ON source_conflicts(post_occurrence_pk)`,
	`CREATE INDEX idx_source_conflicts_existing_post_fk ON source_conflicts(existing_post_occurrence_pk)`,
	`CREATE UNIQUE INDEX idx_source_conflicts_position_unique ON source_conflicts(batch_pk, conflict_position)`,
	`CREATE INDEX idx_source_conflict_candidate_product_evidence_parent_fk ON source_conflict_candidate_product_evidence(source_conflict_pk)`,
	`CREATE UNIQUE INDEX idx_source_conflict_candidate_product_evidence_position_unique ON source_conflict_candidate_product_evidence(source_conflict_pk, evidence_position)`,
	`CREATE INDEX idx_source_conflict_candidate_buyer_intent_evidence_parent_fk ON source_conflict_candidate_buyer_intent_evidence(source_conflict_pk)`,
	`CREATE UNIQUE INDEX idx_source_conflict_candidate_buyer_intent_evidence_position_unique ON source_conflict_candidate_buyer_intent_evidence(source_conflict_pk, evidence_position)`,
	`CREATE INDEX idx_source_conflict_reasons_parent_fk ON source_conflict_reasons(source_conflict_pk)`,
	`CREATE UNIQUE INDEX idx_source_conflict_reasons_position_unique ON source_conflict_reasons(source_conflict_pk, reason_position)`,
	`CREATE INDEX idx_group_summaries_batch_fk ON group_summaries(batch_pk)`,
	`CREATE INDEX idx_group_summaries_group_fk ON group_summaries(group_pk)`,
	`CREATE UNIQUE INDEX idx_group_summaries_position_unique ON group_summaries(batch_pk, group_position)`,
}
